FROM python:3.10

RUN echo "[global]\nindex-url = https://pypi.tuna.tsinghua.edu.cn/simple" > /etc/pip.conf

RUN pip install --upgrade pip

RUN pip install "xinference[all]"

EXPOSE 9997

CMD ["xinference-local", "--host", "0.0.0.0", "--port", "9997"]
